apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      # Retornando para a configuração de rede padrão do cluster
      dnsPolicy: ClusterFirst
      containers:
      - name: payment-service
        image: origemglobaltecnologia/origem-payment:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DB_URL
          value: jdbc:h2:mem:paymentdb
        - name: DB_USERNAME
          value: sa
        - name: DB_PASSWORD
          value: ""
        - name: SERVER_PORT
          value: "8080"
        - name: CORS_ALLOWED_ORIGINS
          value: "http://localhost:3000,http://10.0.0.81:30080"
        - name: RABBIT_URL
          value: "amqps://eglojydb:YJAne6ylmzLLswXLoQfVeFFTwYlAUY2G@jaragua.lmq.cloudamqp.com/eglojydb"
